<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-content">
                <a href="/calendar/manager-calendar/manage" class="btn btn-primary">Agregar Calendario</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <?php foreach ($calendars as $calendar): ?>
        <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">

            <div class="card" data-count="4">
                <div class="card-header" data-background-color="blue" data-header-animation="true">

                    <h5 class="card-title text-center"><i
                                class="material-icons cubeIcon">date_range</i> <?php echo $calendar->getName(); ?></h5>
                </div>
                <div class="card-content text-center">
                    <a href="/calendar/manager-calendar/manage/<?php echo $calendar->getId(); ?>"
                       class="material-icons text-success" rel="tooltip" data-original-title="Configuración"
                       data-placement="top">
                        settings</a>

                </div>

                <div class="card-footer">
                    <p class="stats"><?php echo $calendar->getDescription(); ?></p>
                </div>
            </div>

        </div>


    <?php endforeach; ?>
</div>
