<div class="row">

    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/zfmc/manager-calendar/list">
            <div class="card card-chart" data-count="6">
                <div class="card-header" data-background-color="purple" data-header-animation="true">
                    <i class="material-icons cubeIcon">date_range</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Calendarios</h4>
                </div>
            </div>
        </a>
    </div>


    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/zfmc/holiday/grid">
            <div class="card card-chart" data-count="6">
                <div class="card-header" data-background-color="purple" data-header-animation="true">
                    <i class="material-icons cubeIcon">work_off</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Feriados</h4>
                </div>
            </div>
        </a>
    </div>


    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/zfmc/ticket-schedule/schedule">
            <div class="card card-chart" data-count="6">
                <div class="card-header" data-background-color="purple" data-header-animation="true">
                    <i class="material-icons cubeIcon">widgets</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Programación de  Tickets</h4>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/zfmc/ticket/grid">
            <div class="card card-chart" data-count="6">
                <div class="card-header" data-background-color="purple" data-header-animation="true">
                    <i class="material-icons cubeIcon">list</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Tickets</h4>
                </div>
            </div>
        </a>
    </div>

</div>


<style>
    .cubeIcon {
        position: relative;
        text-align: center;
        width: 100%;
        font-size: 80px;
        margin-top: 15px;
        margin-bottom: 10px;
    }
</style>